version: "3.8"
services:
  redis-server:
    image: registry.community.greenbone.net/community/redis-server
    restart: on-failure
    volumes:
      - redis_socket_vol:/run/redis/

  pg-gvm:
    image: registry.community.greenbone.net/community/pg-gvm:stable
    restart: on-failure
    volumes:
      - psql_data_vol:/var/lib/postgresql
      - psql_socket_vol:/var/run/postgresql

  gvmd:
    image: registry.community.greenbone.net/community/gvmd:stable
    restart: on-failure
    volumes:
      - gvmd_data_vol:/var/lib/gvm
      - scap_data_vol:/var/lib/gvm/scap-data/     # korzysta z istniejącego volume
      - cert_data_vol:/var/lib/gvm/cert-data
      - data_objects_vol:/var/lib/gvm/data-objects/gvmd
      - vt_data_vol:/var/lib/openvas/plugins
      - psql_data_vol:/var/lib/postgresql
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
      - psql_socket_vol:/var/run/postgresql
    depends_on:
      - pg-gvm

  ospd-openvas:
    image: registry.community.greenbone.net/community/ospd-openvas:stable
    restart: on-failure
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    volumes:
      - gpg_data_vol:/etc/openvas/gnupg   # jeśli nie potrzebujesz notus/scap itp., możesz je również usunąć
      - vt_data_vol:/var/lib/openvas/plugins
      - notus_data_vol:/var/lib/notus
      - ospd_openvas_socket_vol:/run/ospd
      - redis_socket_vol:/run/redis/
    depends_on:
      - redis-server
      - gvmd

  # Twój controller (nmap + gvm-script + email)
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: bso-controller
    network_mode: host    # potrzebne do nmap-discovery
    depends_on:
      - gvmd
      - ospd-openvas

volumes:
  redis_socket_vol:
  psql_data_vol:
  psql_socket_vol:
  gvmd_data_vol:
  vt_data_vol:
  scap_data_vol:
  cert_data_vol:
  data_objects_vol:
  notus_data_vol:
  ospd_openvas_socket_vol:
  gpg_data_vol:
