services:
  # Baza danych GVM
  pg-gvm:
    image: registry.community.greenbone.net/community/pg-gvm:stable
    restart: on-failure
    volumes:
      - psql_data_vol:/var/lib/postgresql
      - psql_socket_vol:/var/run/postgresql

  # Redis (wymagany przez OSPD)
  redis-server:
    image: registry.community.greenbone.net/community/redis-server
    restart: on-failure
    volumes:
      - redis_socket_vol:/run/redis/

  # Menedżer skanów
  gvmd:
    image: registry.community.greenbone.net/community/gvmd:stable
    restart: on-failure
    volumes:
      - gvmd_data_vol:/var/lib/gvm
      - psql_data_vol:/var/lib/postgresql
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
      - psql_socket_vol:/var/run/postgresql
      - /etc/ssl/certs/:/etc/ssl/certs:ro
    env_file:
      - .env
    depends_on:
      - pg-gvm

  # Silnik skanowania OpenVAS (przez OSPD)
  ospd-openvas:
    image: registry.community.greenbone.net/community/ospd-openvas:stable
    restart: on-failure
    hostname: ospd-openvas.local
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    command:
      [
        "ospd-openvas",
        "-f",
        "--config",
        "/etc/gvm/ospd-openvas.conf",
        "-m", "666"
      ]
    volumes:
      - vt_data_vol:/var/lib/openvas/plugins
      - ospd_openvas_socket_vol:/run/ospd
      - redis_socket_vol:/run/redis/

  # Nasz kontroler (gvm-cli)
  gvm-cli:
    image: registry.community.greenbone.net/community/gvm-tools
    container_name: greenbone-cli
    entrypoint: ["tail", "-f", "/dev/null"]
    #user: "1001:1001"
    volumes:
      - ./scripts:/opt/scripts:ro
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
      - /etc/ssl/certs/:/etc/ssl/certs:ro
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - gvmd
      - ospd-openvas

volumes:
  psql_data_vol:
  psql_socket_vol:
  redis_socket_vol:
  gvmd_data_vol:
  gvmd_socket_vol:
  ospd_openvas_socket_vol:
  vt_data_vol:
